# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 00:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tina', '0003_auto_20161230_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='humidity',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2016, 12, 31)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2016, 12, 31)),
            preserve_default=False,
        ),
    ]
