# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tina', '0004_auto_20161231_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidity',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
